# Site settings
title: HipSci
email: hipsci-dcc@ebi.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  HipSci brings  together diverse constituents in genomics, proteomics, cell biology and clinical genetics to create a UK national iPS cell resource and use it to carry out cellular genetic studies.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hipsci.org" # the base hostname & protocol for your site
#url: "http://hipsci.github.io" # the base hostname & protocol for your site
#url: "http://test.hipsci.org" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: /:categories/:title
gems:
    - jekyll-redirect-from
collections:
    participants :
        output: false
    mojo_templates :
        output: true
        permalink: /_mojo_templates/:path.html.ep
defaults:
    -
        scope:
            type: "posts"
        values:
            include_in_search: true
    -
        scope:
            type: mojo_templates
        values:
            is_mojo_template: true

# Build settings
markdown: kramdown
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

default_title_element: HipSci | Human Induced Pluripotent Stem Cell Initiative
default_sitemap_lastmod: 2015-10-30T00:00:00+00:00
